#---
#spring:
#  profiles:
#    active: peer1
#server:
#  port: 8761
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: peer1

  client:
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/

    fetchRegistry: true # 获取注册列表
    registerWithEureka: true # 是否将自己也注册到其他eureka节点上。一般设置为true或者默认即可，这样才会在eureka控制台上看到所有的eureka集群列表信息

#---
#spring:
#  profiles:
#    active: peer2
#server:
#  port: 8762
#eureka:
#  instance:
#    hostname: peer2
#
#  client:
#    serviceUrl:
#      defaultZone: http://peer1:8761/eureka/
#
#    fetchRegistry: false # 获取注册列表
#    registerWithEureka: false # 是否将自己也注册到其他eureka节点上。一般设置为true或者默认即可，这样才会在eureka控制台上看到所有的eureka集群列表信息
